name: CI

on:
    push:
        branches:
            - "master"
            - "develop"
    pull_request:
        types: [ready_for_review, synchronize, opened]

jobs:
    conflicts:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - name: Merge Conflict finder
              uses: olivernybroe/action-conflict-finder@v1.1
    sdk:
        needs: [conflicts]
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14.x]
        concurrency:
            group: ${{ github.head_ref }}-sdk
            cancel-in-progress: true
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install
              run: npm ci
            - name: Test
              run: npm run test
